
import java.util.Date;

/**
 *
 * @author User
 */
public class gotorecipt extends javax.swing.JFrame {
gotomain gomain=new gotomain();

    
    public gotorecipt() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        yesgoreciptbtn = new javax.swing.JButton();
        nogoreciptbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Do You Need A Recipt ");
        jLabel1.setToolTipText("");

        yesgoreciptbtn.setBackground(new java.awt.Color(0, 255, 204));
        yesgoreciptbtn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        yesgoreciptbtn.setText("YES");
        yesgoreciptbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesgoreciptbtnActionPerformed(evt);
            }
        });

        nogoreciptbtn.setBackground(new java.awt.Color(0, 255, 204));
        nogoreciptbtn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        nogoreciptbtn.setText("NO");
        nogoreciptbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nogoreciptbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(155, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(yesgoreciptbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nogoreciptbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yesgoreciptbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nogoreciptbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(128, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void yesgoreciptbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesgoreciptbtnActionPerformed
        try {
            Recipt newj= new Recipt();
Recipt.TextArea.setText("     ********************\n");
Recipt.TextArea.setText(Recipt.TextArea.getText()+"     *        BOC       *\n");
Recipt.TextArea.setText(Recipt.TextArea.getText()+"     ********************\n\n");
Recipt.TextArea.setText(Recipt.TextArea.getText()+"DATE          TIME       \n");
        Date date =new Date();
String obj=date.toString();
Recipt.TextArea.setText(Recipt.TextArea.getText()+obj+"\n");
String recordno=Record.getrecord();
Recipt.TextArea.setText(Recipt.TextArea.getText()+" RECORD NO    "+recordno+"\n");
if(otheramount.othwithdraw==true){
Recipt.TextArea.setText(Recipt.TextArea.getText()+"WITHDRAWL     "+otheramount.otheramount+"\n");
Recipt.TextArea.setText(Recipt.TextArea.getText()+"LEDGER BAL    "+otheramount.finalamount+"\n");
Recipt.TextArea.setText(Recipt.TextArea.getText()+"AVAIL BAL     "+otheramount.othAccBal+"\n"+"\n");
}else if(oadepositfield.OthAccDepo){
Recipt.TextArea.setText(Recipt.TextArea.getText()+"ACC NO        "+anotheraccount.AAN+"\n");
Recipt.TextArea.setText(Recipt.TextArea.getText()+"DEPOSIT       "+oadepositfield.Depositamo+"\n"+"\n");
}else if(depositfield.depositbool){
Recipt.TextArea.setText(Recipt.TextArea.getText()+"DEPOSIT       "+depositfield.DepositAmo+"\n");
Recipt.TextArea.setText(Recipt.TextArea.getText()+"AVAIL BAL     "+depositfield.finalbalance+"\n"+"\n");
}else if(withdraw.withdraw){
Recipt.TextArea.setText(Recipt.TextArea.getText()+"WITHDRAWL     "+withdraw.amount+"\n");
Recipt.TextArea.setText(Recipt.TextArea.getText()+"LEDGER BAL    "+withdraw.finalamount+"\n");
Recipt.TextArea.setText(Recipt.TextArea.getText()+"AVAIL BAL     "+withdraw.AccBal+"\n"+"\n");
}
Recipt.TextArea.setText(Recipt.TextArea.getText()+"TRANSACTION IS SUCCESSFUL\n");
Recipt.TextArea.setText(Recipt.TextArea.getText()+"THANKS FOR USING OUR ATM\n");
Recipt.TextArea.setText(Recipt.TextArea.getText()+"CALL CENTER +94112204567\n");
newj.setVisible(true);
this.dispose();
        } catch (Exception e) {
e.printStackTrace();
        }

    }//GEN-LAST:event_yesgoreciptbtnActionPerformed

    private void nogoreciptbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nogoreciptbtnActionPerformed
        gomain.setVisible(true);
this.dispose();
    }//GEN-LAST:event_nogoreciptbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gotorecipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gotorecipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gotorecipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gotorecipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gotorecipt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton nogoreciptbtn;
    private javax.swing.JButton yesgoreciptbtn;
    // End of variables declaration//GEN-END:variables
}
